# Generated by Django 5.2 on 2025-04-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project1", "0003_migrate_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "topics",
            },
        ),
    ]
