# Generated by Django 5.1.6 on 2025-04-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_migrate_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'managed': True},
        ),
    ]
