# Generated by Django 5.1.6 on 2025-04-12 23:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_alter_posts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follows',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='retweets',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='posts',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.authuser'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 12, 23, 41, 32, 941683, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
